### ISSUE TITLE
RuntimeError: CUDA driver error: invalid argument or shape mismatch

### ISSUE THREAD

**Issue by JOY-SWang** [xiaomi-research/r1-aqa#36]
- First TRY with bugs：
{'loss': 0.0066, 'grad_norm': 21.37458038330078, 'learning_rate': 9.89e-07, 'completion_length': 306.9375, 'rewards/accuracy_reward': 0.0, 'rewards/format_reward': 0.0, 'reward': 0.0, 'reward_std': 0.0, 'kl': 0.167236328125, 'epoch': 0.19}
  1%|█▎                                                                                                                          | 11/1000 [03:22<4:41:30, 17.08s/it]Expanding inputs for audio tokens in Qwen2Audio should be done in processing.
[rank4]: Traceback (most recent call last):
[rank4]:     main()
[rank4]:     trainer.train()
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2241, in train
[rank4]:     return inner_training_loop(
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2548, in _inner_training_loop
[rank4]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 3698, in training_step
[rank4]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank4]:   File ".../r1-aqa-main/src/trainer/grpo_trainer.py", line 358, in compute_loss
[rank4]:     prompt_completion_ids = unwrapped_model.generate(**prompt_inputs, generation_config=self.generation_config)
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank4]:     return func(*args, **kwargs)
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2223, in generate
[rank4]:     result = self._sample(
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3211, in _sample
[rank4]:     outputs = self(**model_inputs, return_dict=True)
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1845, in _call_impl
[rank4]:     return inner()
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1793, in inner
[rank4]:     result = forward_call(*args, **kwargs)
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 1199, in forward
[rank4]:     inputs_embeds, attention_mask, labels, position_ids, _ = self._merge_input_ids_with_audio_features(
[rank4]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 1027, in _merge_input_ids_with_audio_features
[rank4]:     token_placeholder_num[special_audio_token_mask] = num_audio_tokens.long() - 1
**[rank4]: RuntimeError: shape mismatch: value tensor of shape [8] cannot be broadcast to indexing result of shape [0]**

- Second Try with bugs：
  0%|▌                                                                                                                            | 4/1000 [01:21<5:21:23, 19.36s/it]Invalidate trace cache @ step 0 and module 7840: cache has only 0 modules
[rank0]: Traceback (most recent call last):
[rank0]:     main()
[rank0]:     trainer.train()
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2241, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2548, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 3698, in training_step
[rank0]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank0]:   File ".../r1-aqa-main/src/trainer/grpo_trainer.py", line 384, in compute_loss
[rank0]:     ref_per_token_logps = self._get_per_token_logps(self.ref_model, prompt_completion_ids, attention_mask, features_values, features_masks)
[rank0]:   File ".../code/r1-aqa-main/src/trainer/grpo_trainer.py", line 320, in _get_per_token_logps
[rank0]:     logits = model(input_ids, attention_mask=attention_mask, input_features=features_values, feature_attention_mask=features_masks).logits  # (B, L, V)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1914, in forward
[rank0]:     loss = self.module(*inputs, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1845, in _call_impl
[rank0]:     return inner()
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1793, in inner
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 1220, in forward
[rank0]:     outputs = self.language_model(
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1845, in _call_impl
[rank0]:     return inner()
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1793, in inner
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 873, in forward
[rank0]:     logits = self.lm_head(hidden_states[:, slice_indices, :])
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1845, in _call_impl
[rank0]:     return inner()
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1793, in inner
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 125, in forward
[rank0]:     return F.linear(input, self.weight, self.bias)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py", line 116, in zero3_linear_wrap
[rank0]:     return LinearFunctionForZeroStage3.apply(input, weight)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 503, in decorate_fwd
[rank0]:     return fwd(*args, **kwargs)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py", line 64, in forward
**[rank0]:     output = input.matmul(weight.t())**
**[rank0]: RuntimeError: CUDA driver error: invalid argument**

my environment:
A800*8, CPU memory = 1.9TB.
python 3.10, cuda 12.2

**Comment by GrantL10** [comment]
I think the error doesn't come from CUDA. Did you make any changes to the code?

**Comment by JOY-SWang** [comment]
I've only changed DATA_FILE and MODEL_NP in run_grpo.sh

**Comment by JOY-SWang** [comment]
I refork the repository, and rerun ```sh run_grpo.sh```, but still get the same problem.

**Comment by GrantL10** [comment]
Honestly, the shape mismatch usually comes from the corrupted data. I suggest checking if the audio and metadata (JSONL) are functioning properly.

**Comment by JOY-SWang** [comment]
I've solved it by checking the audio. VGG-Sound consists of both audio and video. Each segment is 10 seconds long. 
So all the audio should be downloaded from the start_seconds to {start_seconds+10}.
